# permissions for end users to edit domains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: domain-editor-role
rules:
- apiGroups:
  - backstage.io
  resources:
  - domains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backstage.io
  resources:
  - domains/status
  verbs:
  - get
