# permissions for end users to edit locations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: location-editor-role
rules:
- apiGroups:
  - backstage.io
  resources:
  - locations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backstage.io
  resources:
  - locations/status
  verbs:
  - get
