# permissions for end users to view locations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: location-viewer-role
rules:
- apiGroups:
  - backstage.io
  resources:
  - locations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backstage.io
  resources:
  - locations/status
  verbs:
  - get
